name: doc-edited

on:
  push:
    branches:
      - '*'

jobs:
 doc-edited:
   strategy:
     matrix:
       os: [ubuntu-latest, macos-latest, windows-latest]
       python-version: ['3.10', 3.9, 3.8, 3.7]
   runs-on: ${{ matrix.os }}
   steps:
    - name: Checkout Master
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 1000

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1000
    


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check doc
      id: check_doc
      run: |
        pip install git+https://github.com/mehtamohit013/pkgmt.git@doc
        python -m pkgmt.fail_if_modified -b origin/pkgmt_modi -e doc
      continue-on-error: true
    
    - name: Only Doc Testing
      if: steps.check_doc.outcome == 'success'
      run: |
        echo "Only Doc Testing"
    
    - name: All Testing
      if: steps.check_doc.outcome == 'failure'
      run: |
        echo "All Testing"
