name: changelog-edited

on:
  push:
    branches:
      - '*'

jobs:
 changelog-edited:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: git remote branches
      run: git branch -r

    - name: git local branches
      run: git branch
      

    # TODO: set BRANCH_NAME depending on which is the default branch
    - name: Check doc
      id: check_doc
      run: |
        pip install git+https://github.com/mehtamohit013/pkgmt.git@doc
        python -m pkgmt.modified -b origin/pkgmt_modi -e doc
      continue-on-error: true
    
    - name: Only Doc Testing
      if: steps.check_doc.outcome == 'success'
      run: |
        echo "Only Doc Testing"
    
    - name: All Testing
      if: steps.check_doc.outcome == 'failure'
      run: |
        echo "All Testing"
